
import java.awt.event.KeyEvent;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Gesa Rizky Nugraha
 */
public class Framepercepat extends javax.swing.JFrame {

    /**
     * Creates new form Framepercepat
     */
    public Framepercepat() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        inv1 = new javax.swing.JTextField();
        inv2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        int1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        int2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        outselv = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        outselt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        outa = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("KALKULATOR RUMUS PERCEPATAN");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Isi data kecepatan awal , kecepatan akhir, waktu awal dan waktu akhir");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Kecepatan Awal ");

        inv1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        inv1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inv1ActionPerformed(evt);
            }
        });
        inv1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inv1KeyTyped(evt);
            }
        });

        inv2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        inv2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inv2ActionPerformed(evt);
            }
        });
        inv2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inv2KeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Kecepatan Akhir");

        int1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        int1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                int1ActionPerformed(evt);
            }
        });
        int1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                int1KeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Waktu Awal");

        int2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        int2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                int2ActionPerformed(evt);
            }
        });
        int2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                int2KeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Waktu Akhir");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Hasilnya :");

        outselv.setEditable(false);
        outselv.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Perubahan Kecepatan");

        outselt.setEditable(false);
        outselt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Selang Waktu");

        outa.setEditable(false);
        outa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Percepatan");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(152, Short.MAX_VALUE))
            .addComponent(jSeparator1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(inv1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(outselt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(outa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                            .addComponent(outselv, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(int2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(inv2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(int1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(inv1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(inv2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(int1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(int2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(outselv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(outselt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(outa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void int2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_int2ActionPerformed
        // TODO add your handling code here:
        if (inv1.getText().equals("") || inv2.getText().equals("") || int1.getText().equals("") || int2.getText().equals("")) {
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "isi semua data");
        } else {
            DecimalFormat df = new DecimalFormat("#.##");
            String teksv1 = inv1.getText();
            double inputv1 = Double.parseDouble(teksv1);
            String teksv2 = inv2.getText();
            double inputv2 = Double.parseDouble(teksv2);
            String tekst1 = int1.getText();
            double inputt1 = Double.parseDouble(tekst1);
            String tekst2 = int2.getText();
            double inputt2 = Double.parseDouble(tekst2);
            double hasilselv = inputv2 - inputv1;
            String outputselv = df.format(hasilselv);
            outselv.setText(outputselv);
            double hasilselt = inputt2 - inputt1;
            String outputselt = df.format(hasilselt);
            outselt.setText(outputselt);
            double hasila = hasilselv / hasilselt;
            String outputa = df.format(hasila);
            outa.setText(outputa);
        }
    }//GEN-LAST:event_int2ActionPerformed

    private void inv1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inv1ActionPerformed
        // TODO add your handling code here:
        if (inv1.getText().equals("") || inv2.getText().equals("") || int1.getText().equals("") || int2.getText().equals("")) {
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "isi semua data");
        } else {
            DecimalFormat df = new DecimalFormat("#.##");
            String teksv1 = inv1.getText();
            double inputv1 = Double.parseDouble(teksv1);
            String teksv2 = inv2.getText();
            double inputv2 = Double.parseDouble(teksv2);
            String tekst1 = int1.getText();
            double inputt1 = Double.parseDouble(tekst1);
            String tekst2 = int2.getText();
            double inputt2 = Double.parseDouble(tekst2);
            double hasilselv = inputv2 - inputv1;
            String outputselv = df.format(hasilselv);
            outselv.setText(outputselv);
            double hasilselt = inputt2 - inputt1;
            String outputselt = df.format(hasilselt);
            outselt.setText(outputselt);
            double hasila = hasilselv / hasilselt;
            String outputa = df.format(hasila);
            outa.setText(outputa);
        }
    }//GEN-LAST:event_inv1ActionPerformed

    private void inv2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inv2ActionPerformed
        // TODO add your handling code here:
        if (inv1.getText().equals("") || inv2.getText().equals("") || int1.getText().equals("") || int2.getText().equals("")) {
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "isi semua data");
        } else {
            DecimalFormat df = new DecimalFormat("#.##");
            String teksv1 = inv1.getText();
            double inputv1 = Double.parseDouble(teksv1);
            String teksv2 = inv2.getText();
            double inputv2 = Double.parseDouble(teksv2);
            String tekst1 = int1.getText();
            double inputt1 = Double.parseDouble(tekst1);
            String tekst2 = int2.getText();
            double inputt2 = Double.parseDouble(tekst2);
            double hasilselv = inputv2 - inputv1;
            String outputselv = df.format(hasilselv);
            outselv.setText(outputselv);
            double hasilselt = inputt2 - inputt1;
            String outputselt = df.format(hasilselt);
            outselt.setText(outputselt);
            double hasila = hasilselv / hasilselt;
            String outputa = df.format(hasila);
            outa.setText(outputa);
        }
    }//GEN-LAST:event_inv2ActionPerformed

    private void int1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_int1ActionPerformed
        // TODO add your handling code here:
        if (inv1.getText().equals("") || inv2.getText().equals("") || int1.getText().equals("") || int2.getText().equals("")) {
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "isi semua data");
        } else {
            DecimalFormat df = new DecimalFormat("#.##");
            String teksv1 = inv1.getText();
            double inputv1 = Double.parseDouble(teksv1);
            String teksv2 = inv2.getText();
            double inputv2 = Double.parseDouble(teksv2);
            String tekst1 = int1.getText();
            double inputt1 = Double.parseDouble(tekst1);
            String tekst2 = int2.getText();
            double inputt2 = Double.parseDouble(tekst2);
            double hasilselv = inputv2 - inputv1;
            String outputselv = df.format(hasilselv);
            outselv.setText(outputselv);
            double hasilselt = inputt2 - inputt1;
            String outputselt = df.format(hasilselt);
            outselt.setText(outputselt);
            double hasila = hasilselv / hasilselt;
            String outputa = df.format(hasila);
            outa.setText(outputa);
        }
    }//GEN-LAST:event_int1ActionPerformed

    private void inv1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inv1KeyTyped
        // TODO add your handling code here:
        char karakter = evt.getKeyChar();
        if (!(((karakter >= '0') && (karakter <= '9') || (karakter == KeyEvent.VK_BACK_SPACE) || (karakter == KeyEvent.VK_DELETE) || (karakter == '.')))) {
            evt.consume();
        }
    }//GEN-LAST:event_inv1KeyTyped

    private void inv2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inv2KeyTyped
        // TODO add your handling code here:
        char karakter = evt.getKeyChar();
        if (!(((karakter >= '0') && (karakter <= '9') || (karakter == KeyEvent.VK_BACK_SPACE) || (karakter == KeyEvent.VK_DELETE) || (karakter == '.')))) {
            evt.consume();
        }
    }//GEN-LAST:event_inv2KeyTyped

    private void int1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_int1KeyTyped
        // TODO add your handling code here:
        char karakter = evt.getKeyChar();
        if (!(((karakter >= '0') && (karakter <= '9') || (karakter == KeyEvent.VK_BACK_SPACE) || (karakter == KeyEvent.VK_DELETE) || (karakter == '.')))) {
            evt.consume();
        }
    }//GEN-LAST:event_int1KeyTyped

    private void int2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_int2KeyTyped
        // TODO add your handling code here:
        char karakter = evt.getKeyChar();
        if (!(((karakter >= '0') && (karakter <= '9') || (karakter == KeyEvent.VK_BACK_SPACE) || (karakter == KeyEvent.VK_DELETE) || (karakter == '.')))) {
            evt.consume();
        }
    }//GEN-LAST:event_int2KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Framepercepat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Framepercepat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Framepercepat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Framepercepat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Framepercepat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField int1;
    private javax.swing.JTextField int2;
    private javax.swing.JTextField inv1;
    private javax.swing.JTextField inv2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField outa;
    private javax.swing.JTextField outselt;
    private javax.swing.JTextField outselv;
    // End of variables declaration//GEN-END:variables
}
